name: Docker Image CI

on:
  push:
    branches: 
            - "main"
            - "girishchawla202-patch-1"
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: install dependencies 
      run : sudo apt-get python | pytest alluredir=allure-dirc
